In [1]:
import numpy as np

# reproducibility
rng = np.random.default_rng(0)

# make random positive definite A,B so (A+B) is invertible
n = 3
A = rng.standard_normal((n,n))
A = A @ A.T + np.eye(n)  # SPD
B = rng.standard_normal((n,n))
B = B @ B.T + np.eye(n)

lhs = A @ np.linalg.inv(A + B) @ B
rhs = B - B @ np.linalg.inv(A + B) @ B

print("LHS:\n", lhs)
print("RHS:\n", rhs)
print("Difference (LHS - RHS):\n", lhs - rhs)
print("‖difference‖₂ =", np.linalg.norm(lhs - rhs))


LHS:
 [[0.82895307 0.2600871  0.11241188]
 [0.2600871  1.07526162 0.08299173]
 [0.11241188 0.08299173 0.9423594 ]]
RHS:
 [[0.82895307 0.2600871  0.11241188]
 [0.2600871  1.07526162 0.08299173]
 [0.11241188 0.08299173 0.9423594 ]]
Difference (LHS - RHS):
 [[ 3.33066907e-16  1.11022302e-16 -1.38777878e-17]
 [ 3.88578059e-16  1.11022302e-15  3.05311332e-16]
 [ 0.00000000e+00  1.24900090e-16  0.00000000e+00]]
‖difference‖₂ = 1.2711629413025267e-15
